In [54]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

# 最大表示列数の指定（ここでは50列を指定）
pd.set_option("display.max_columns", 1000)
pd.set_option("display.max_rows", 1000)

import warnings
warnings.filterwarnings("ignore")

In [55]:
path = "../input/pickle/"

train = pd.read_pickle(path + "train.zip")
train_x = train.drop(["y"], axis=1)
train_y = train["y"]
test_x = pd.read_pickle(path + "test.zip")

In [56]:
train_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 543133 entries, 0 to 543132
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   year               543133 non-null  int64
 1   month              543133 non-null  int64
 2   shopID             543133 non-null  int64
 3   itemID             543133 non-null  int64
 4   item_categoryID    543133 non-null  int64
 5   item_category_big  543133 non-null  int64
 6   item_price         543133 non-null  int64
 7   release_time       543133 non-null  float64
dtypes: float64(1), int64(7)
memory usage: 37.3 MB

In [57]:
test_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3060 entries, 0 to 3059
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   itemID             3060 non-null   int64
 1   shopID             3060 non-null   int64
 2   item_categoryID    3060 non-null   int64
 3   item_category_big  3060 non-null   int64
 4   month              3060 non-null   int64
 5   year               3060 non-null   int64
 6   item_price         3060 non-null   float64
 7   release_time       3060 non-null   int64
dtypes: float64(1), int64(7)
memory usage: 215.2 KB

In [58]:
train_x

,year,month,shopID,itemID,item_categoryID,item_category_big,item_price,release_time
0,2018,1,0,1000001,100,5,420,12.6
1,2018,1,0,1000002,100,5,250,10.0
2,2018,1,0,1000004,100,5,120,15.0
3,2018,1,0,1000005,100,5,130,11.5
4,2018,1,0,1000005,100,5,250,12.0
...,...,...,...,...,...,...,...,...
543128,2019,10,17,3400005,340,4,1190,661.0
543129,2019,10,17,3400006,340,4,2700,642.0
543130,2019,10,17,3400012,340,4,680,639.0
543131,2019,10,17,3400016,340,4,250,141.0
543132,2019,10,17,3500073,350,6,420,0.0

In [59]:
test_x

,itemID,shopID,item_categoryID,item_category_big,month,year,item_price,release_time
0,1000001,0,100,5,12,2019,250.0,713
1,1000001,1,100,5,12,2019,420.0,713
2,1000001,2,100,5,12,2019,250.0,713
3,1000001,3,100,5,12,2019,250.0,713
4,1000001,4,100,5,12,2019,250.0,713
...,...,...,...,...,...,...,...,...
3055,3500001,13,350,6,12,2019,420.0,703
3056,3500001,14,350,6,12,2019,420.0,703
3057,3500001,15,350,6,12,2019,200.0,703
3058,3500001,16,350,6,12,2019,420.0,703
3059,3500001,17,350,6,12,2019,420.0,703

In [60]:
train_x.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            543123, 543124, 543125, 543126, 543127, 543128, 543129, 543130,
            543131, 543132],
           dtype='int64', length=543133)

In [61]:
years = [2018] * 6 + [2019] * 9
months = list(range(7, 13)) + list(range(1, 10))

In [62]:
month_list = list(range(1, 7))
year_list = [2017] + [2018]

scores = []

# custom function to run light gbm model
def run_lgb(train_X, train_y, val_X, val_y, x_test):
    params = {"objective" : "regression", 
              "metric" : "rmse", 
              "n_estimators":20000, 
              "early_stopping_rounds":200,
              "num_leaves" : 31, 
              "learning_rate" : 0.01, 
              "bagging_fraction" : 0.7,
              "bagging_seed" : 0, 
              "num_threads" : 4,
              "colsample_bytree" : 0.7,
              'max_depth': 5
             }
    
    lgtrain = lgb.Dataset(tr_x, tr_y)
    lgval = lgb.Dataset(va_x, va_y)
    model = lgb.train(params, lgtrain, 
                      valid_sets=[lgtrain, lgval], 
                      verbose_eval=1000)
    
    pred_test_y = model.predict(x_test, num_iteration=model.best_iteration)
    return pred_test_y, model

for year, month in zip(years, months):
    if year == 2019 and len(year_list) == 1:
        year_list = year_list.append(year)
    
    month_list.append(month)
    
    if month == 12:
        year += 1
        month = 1
    
    tr_x = train_x[(train_x["year"].isin(year_list))&(train_x["month"].isin(month_list))]
    va_x = train_x[(train_x["year"] == year)&(train_x["month"] == month)]
    tr_y, va_y = train_y.iloc[tr_x.index], train_y.iloc[va_x.index]
    
    # Training the model
    pred_test, model = run_lgb(tr_x, tr_y, va_x, va_y, test_x)
    
    # バリデーションデータでのスコアの確認
    va_pred = model.predict(va_x)
    score = np.sqrt(mean_squared_error(va_y, va_pred))
    
    scores.append(score)

Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.4713	valid_1's rmse: 2.96024
[2000]	training's rmse: 3.19759	valid_1's rmse: 2.79128
[3000]	training's rmse: 3.05048	valid_1's rmse: 2.70889
[4000]	training's rmse: 2.95314	valid_1's rmse: 2.62683
[5000]	training's rmse: 2.88038	valid_1's rmse: 2.57244
[6000]	training's rmse: 2.83457	valid_1's rmse: 2.53868
[7000]	training's rmse: 2.8047	valid_1's rmse: 2.51209
[8000]	training's rmse: 2.77128	valid_1's rmse: 2.48282
[9000]	training's rmse: 2.74302	valid_1's rmse: 2.45948
[10000]	training's rmse: 2.72148	valid_1's rmse: 2.43758
[11000]	training's rmse: 2.69779	valid_1's rmse: 2.42287
[12000]	training's rmse: 2.674	valid_1's rmse: 2.39391
[13000]	training's rmse: 2.65239	valid_1's rmse: 2.37308
[14000]	training's rmse: 2.62442	valid_1's rmse: 2.34946
[15000]	training's rmse: 2.60589	valid_1's rmse: 2.33407
[16000]	training's rmse: 2.58958	valid_1's rmse: 2.32075
[17000]	training's rmse: 2.57331	valid_1's rmse: 2.30139
[18000]	training's rmse: 2.55347	valid_1's rmse: 2.28071
[19000]	training's rmse: 2.54048	valid_1's rmse: 2.26872
[20000]	training's rmse: 2.52832	valid_1's rmse: 2.25765
Did not meet early stopping. Best iteration is:
[20000]	training's rmse: 2.52832	valid_1's rmse: 2.25765
Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.41501	valid_1's rmse: 2.92213
[2000]	training's rmse: 3.20876	valid_1's rmse: 2.77163
[3000]	training's rmse: 3.05337	valid_1's rmse: 2.70147
[4000]	training's rmse: 2.96792	valid_1's rmse: 2.61489
[5000]	training's rmse: 2.90301	valid_1's rmse: 2.56853
[6000]	training's rmse: 2.8506	valid_1's rmse: 2.53069
[7000]	training's rmse: 2.8096	valid_1's rmse: 2.48873
[8000]	training's rmse: 2.77208	valid_1's rmse: 2.44292
[9000]	training's rmse: 2.74233	valid_1's rmse: 2.41885
[10000]	training's rmse: 2.71598	valid_1's rmse: 2.39376
[11000]	training's rmse: 2.69233	valid_1's rmse: 2.36607
[12000]	training's rmse: 2.66883	valid_1's rmse: 2.34428
[13000]	training's rmse: 2.64589	valid_1's rmse: 2.31624
[14000]	training's rmse: 2.6266	valid_1's rmse: 2.29325
[15000]	training's rmse: 2.59974	valid_1's rmse: 2.2737
[16000]	training's rmse: 2.58369	valid_1's rmse: 2.25854
[17000]	training's rmse: 2.56589	valid_1's rmse: 2.24194
[18000]	training's rmse: 2.54593	valid_1's rmse: 2.22884
[19000]	training's rmse: 2.53442	valid_1's rmse: 2.21765
[20000]	training's rmse: 2.51506	valid_1's rmse: 2.2041
Did not meet early stopping. Best iteration is:
[20000]	training's rmse: 2.51506	valid_1's rmse: 2.2041
Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.42501	valid_1's rmse: 3.24194
[2000]	training's rmse: 3.19921	valid_1's rmse: 3.1062
[3000]	training's rmse: 3.06765	valid_1's rmse: 3.00649
[4000]	training's rmse: 2.96965	valid_1's rmse: 2.94124
[5000]	training's rmse: 2.89929	valid_1's rmse: 2.86156
[6000]	training's rmse: 2.85155	valid_1's rmse: 2.80891
[7000]	training's rmse: 2.80836	valid_1's rmse: 2.77384
[8000]	training's rmse: 2.77705	valid_1's rmse: 2.74629
[9000]	training's rmse: 2.74553	valid_1's rmse: 2.72063
[10000]	training's rmse: 2.71767	valid_1's rmse: 2.6919
[11000]	training's rmse: 2.68943	valid_1's rmse: 2.66508
[12000]	training's rmse: 2.66473	valid_1's rmse: 2.64853
[13000]	training's rmse: 2.64551	valid_1's rmse: 2.63072
[14000]	training's rmse: 2.62479	valid_1's rmse: 2.61298
[15000]	training's rmse: 2.60739	valid_1's rmse: 2.60136
[16000]	training's rmse: 2.58928	valid_1's rmse: 2.58629
[17000]	training's rmse: 2.57481	valid_1's rmse: 2.57408
[18000]	training's rmse: 2.55548	valid_1's rmse: 2.55839
[19000]	training's rmse: 2.5373	valid_1's rmse: 2.5435
[20000]	training's rmse: 2.52357	valid_1's rmse: 2.53288
Did not meet early stopping. Best iteration is:
[20000]	training's rmse: 2.52357	valid_1's rmse: 2.53288
Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.50808	valid_1's rmse: 4.13758
[2000]	training's rmse: 3.30548	valid_1's rmse: 3.97264
[3000]	training's rmse: 3.16496	valid_1's rmse: 3.88167
[4000]	training's rmse: 3.08112	valid_1's rmse: 3.80497
[5000]	training's rmse: 3.02442	valid_1's rmse: 3.76092
[6000]	training's rmse: 2.98033	valid_1's rmse: 3.72153
[7000]	training's rmse: 2.94687	valid_1's rmse: 3.69043
[8000]	training's rmse: 2.91368	valid_1's rmse: 3.65551
[9000]	training's rmse: 2.88873	valid_1's rmse: 3.61961
[10000]	training's rmse: 2.86418	valid_1's rmse: 3.58639
[11000]	training's rmse: 2.83693	valid_1's rmse: 3.55991
[12000]	training's rmse: 2.81253	valid_1's rmse: 3.52664
[13000]	training's rmse: 2.79295	valid_1's rmse: 3.50133
[14000]	training's rmse: 2.77341	valid_1's rmse: 3.4766
[15000]	training's rmse: 2.75408	valid_1's rmse: 3.45975
[16000]	training's rmse: 2.73537	valid_1's rmse: 3.43568
[17000]	training's rmse: 2.71746	valid_1's rmse: 3.41182
[18000]	training's rmse: 2.70304	valid_1's rmse: 3.39469
[19000]	training's rmse: 2.68849	valid_1's rmse: 3.37232
[20000]	training's rmse: 2.67643	valid_1's rmse: 3.35375
Did not meet early stopping. Best iteration is:
[20000]	training's rmse: 2.67643	valid_1's rmse: 3.35375
Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.60764	valid_1's rmse: 4.29637
[2000]	training's rmse: 3.39548	valid_1's rmse: 3.85009
[3000]	training's rmse: 3.26366	valid_1's rmse: 3.6018
[4000]	training's rmse: 3.16912	valid_1's rmse: 3.43014
[5000]	training's rmse: 3.10321	valid_1's rmse: 3.32992
[6000]	training's rmse: 3.0529	valid_1's rmse: 3.25414
[7000]	training's rmse: 3.012	valid_1's rmse: 3.1969
[8000]	training's rmse: 2.97232	valid_1's rmse: 3.13588
[9000]	training's rmse: 2.94056	valid_1's rmse: 3.10443
[10000]	training's rmse: 2.91391	valid_1's rmse: 3.07899
[11000]	training's rmse: 2.88828	valid_1's rmse: 3.05052
[12000]	training's rmse: 2.86771	valid_1's rmse: 3.01998
[13000]	training's rmse: 2.84698	valid_1's rmse: 3.00046
[14000]	training's rmse: 2.82106	valid_1's rmse: 2.96312
[15000]	training's rmse: 2.80149	valid_1's rmse: 2.93124
[16000]	training's rmse: 2.78579	valid_1's rmse: 2.90796
[17000]	training's rmse: 2.76735	valid_1's rmse: 2.88937
[18000]	training's rmse: 2.75147	valid_1's rmse: 2.87054
[19000]	training's rmse: 2.73502	valid_1's rmse: 2.84332
[20000]	training's rmse: 2.71887	valid_1's rmse: 2.81609
Did not meet early stopping. Best iteration is:
[20000]	training's rmse: 2.71887	valid_1's rmse: 2.81609
Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.70972	valid_1's rmse: 3.21039
Early stopping, best iteration is:
[1057]	training's rmse: 3.69376	valid_1's rmse: 3.20421
Training until validation scores don't improve for 200 rounds
[1000]	training's rmse: 3.70972	valid_1's rmse: 3.21039
Early stopping, best iteration is:
[1057]	training's rmse: 3.69376	valid_1's rmse: 3.20421
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[128]	training's rmse: 4.12238	valid_1's rmse: 2.8348
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[621]	training's rmse: 3.81358	valid_1's rmse: 3.50748
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[367]	training's rmse: 3.90025	valid_1's rmse: 2.60012
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[367]	training's rmse: 3.90025	valid_1's rmse: 2.68136
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[385]	training's rmse: 3.892	valid_1's rmse: 2.91636
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[157]	training's rmse: 4.07373	valid_1's rmse: 2.39171
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[717]	training's rmse: 3.78623	valid_1's rmse: 2.67682
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[170]	training's rmse: 4.05733	valid_1's rmse: 2.60668

In [67]:
scores

[2.2576540949341473,
 2.2041040992422736,
 2.5328788580454633,
 3.3537457073392254,
 2.8160946182591875,
 3.2042056876587353,
 3.2042056876587353,
 2.8348026555737555,
 3.507482884232313,
 2.6001249837885023,
 2.681361545922712,
 2.9163600432646684,
 2.3917148410545863,
 2.67681609430529,
 2.6066843612010673]

In [63]:
# 予測
pred = model.predict(test_x)

In [65]:
path = "../submission/"

submission = pd.read_csv(path + "sample_submission.csv", header=None)

submission.iloc[:,[1]] = pred
submission.head()

   0         1
0  0  1.598766
1  1  1.602905
2  2  1.598766
3  3  1.588539
4  4  1.588539

In [66]:
submission.to_csv(path + "submission.csv", index=False, header=None)